import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Home: NextPage = () => {
  const { t } = useTranslation('common');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <a href='/ko'>{t('language.ko')}</a>
          <a href="/en">{t('language.en')}</a>
        </nav>
        <h1>{t('title')}</h1>
        <p>{t('description')}</p>
      </main>
    </div>
  )
}

export type LocaleProps = {
  locale: string;
}

export const getStaticProps = async ({ locale }: LocaleProps) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"]))
  }
})

export default Home
